---
name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    env:
      REACT_APP_PANDA_SCORE_API_TOKEN: ${{ secrets.PAND_SCORE_API_TOKEN }}
      REACT_APP_PANDA_SCORE_API_URL: https://easy-reverse-proxy.herokuapp.com
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Build application
        run: |
          npm ci
          CI=false npm run build --if-present
      - name: Deploy Application
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          user_name: 'default-octocat'
          user_email: 'default-octocat@users.noreply.github.com'
